# Generated by Django 3.1.7 on 2021-04-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210404_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='continent',
        ),
    ]
