# Generated by Django 3.1.7 on 2021-04-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210404_1850'),
        ('main_app', '0011_remove_city_continent'),
    ]

    operations = [
    ]
