# Generated by Django 3.1.7 on 2021-04-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20210404_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='person',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
